[project]
name = "api"
version = "0.1.0"
description = ""
authors = [
    {name = "Biz3l",email = "gabrieloliveiralveslegal@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.136.1,<0.137.0)",
    "uvicorn[stable] (>=0.46.0,<0.47.0)",
    "pyjwt (>=2.12.1,<3.0.0)",
    "databases (>=0.9.0,<0.10.0)",
    "sqlalchemy (>=2.0.49,<3.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
